services:
  - type: web
    name: portfolio-backend
    env: node
    nodeVersion: 18.17.0
    rootDir: /portfolio-backend
    buildCommand: |
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb://ritik:Msdhoni7@csk@cluster0-shard-00-00.syymf.mongodb.net:27017,cluster0-shard-00-01.syymf.mongodb.net:27017,cluster0-shard-00-02.syymf.mongodb.net:27017/?replicaSet=atlas-10zw8w-shard-0&ssl=true&authSource=admin&retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: 3f7d9e2b5a8c1f4e6b9d2a7c0f5e8b3a6d9c2f5e8b1a4d7c0f3e6b9d2a5c8f1e4b7d0a3c6f9e2b5d8
      - key: FRONTEND_URL
        value: SET_THIS_IN_RENDER_DASHBOARD 